// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ) => {
      // If we are not running inside an iframe (e.g. running locally in a browser tab),
      // we don't need the Lovable OAuth broker and can redirect directly via Supabase.
      const isInIframe = typeof window !== "undefined" && window.self !== window.top;
      if (!isInIframe) {
        try {
          const supabaseProvider = provider === "microsoft" ? "azure" : provider;
          if (supabaseProvider !== "lovable") {
            const { data, error } = await supabase.auth.signInWithOAuth({
              provider: supabaseProvider as any,
              options: {
                redirectTo: opts?.redirect_uri || window.location.origin,
                queryParams: opts?.extraParams,
              },
            });
            if (error) {
              return { error };
            }
            return { error: null, redirected: true };
          }
        } catch (e) {
          return { error: e instanceof Error ? e : new Error(String(e)) };
        }
      }

      // Inside Lovable Sandbox iframe — use the local dev bridge broker
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
